services:
  connection.factory.elastic:
    class: Vainyl\Elastic\Factory\ElasticConnectionFactory
  database.factory.elastic:
    class: Vainyl\Elastic\Factory\ElasticDatabaseFactory
    arguments: ['@connection.storage']